### ISSUE TITLE
Feature request: Response Body Bytes

### ISSUE THREAD

**Issue by developervariety** [matteocontrini/PlainHttp#2]
Instead of having a response in only one format, a byte array would be appreciated.

**Comment by developervariety** [comment]
If I would've looked a bit further, `.Message` has everything I needed haha.

**Comment by matteocontrini** [comment]
Hi, that's correct, the `HttpResponse` exposes the `System.Net.Http.HttpResponseMessage`, and from that you should be able to access the response content.

Note that the body will still be read to a string unless you set `ReadBody` to false in the request. In that case, however, you would need to read the body manually:

```csharp
byte[] array = await resp.Message.Content.ReadAsByteArrayAsync();
```

There's definitely space for improvement, but honestly I didn't think much about it since the most common use case is probably to read the response as a string :)
